'use client'

import './globals.css'
import {Roboto} from 'next/font/google'

import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import {StoreProvider} from '@/redux/StoreProvider'
import {Metadata} from 'next'

const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<StoreProvider>
					<div id='modal'></div>
					<div id='drop-down'></div>
					<div className={'wrapper'}>
						<Header></Header>

						<main>{children}</main>

						<Footer></Footer>
					</div>
				</StoreProvider>
			</body>
		</html>
	)
}
